export const improvementSummary = {
  categories: [
    { label: 'Total suggestions', value: '08', detail: 'Across the review scope', accent: 'indigo' },
    { label: 'Architecture', value: '02', detail: 'Boundaries and structure', accent: 'blue' },
    { label: 'Security', value: '02', detail: 'Controls to strengthen', accent: 'rose' },
    { label: 'Code quality', value: '02', detail: 'Maintainability actions', accent: 'amber' },
    { label: 'Performance', value: '01', detail: 'Runtime opportunities', accent: 'cyan' },
    { label: 'Documentation', value: '01', detail: 'Context to capture', accent: 'emerald' },
  ],
  priorities: [
    { label: 'High', value: '02', accent: 'rose' },
    { label: 'Medium', value: '04', accent: 'amber' },
    { label: 'Low', value: '02', accent: 'slate' },
  ],
}

export const improvementSuggestions = [
  {
    category: 'Architecture',
    categoryTone: 'blue',
    priority: 'Medium',
    priorityTone: 'amber',
    title: 'Separate database configuration from initialization',
    description: 'Make connection settings and session setup independently understandable as the persistence layer grows.',
    icon: 'database',
    relatedEvidence: 'backend/app/database.py',
    evidenceLabel: 'Related evidence',
    action: 'Move environment reads and engine construction behind a focused database configuration boundary.',
    benefit: 'Improves testability and makes deployment-specific settings easier to reason about.',
  },
  {
    category: 'Architecture',
    categoryTone: 'blue',
    priority: 'Medium',
    priorityTone: 'amber',
    title: 'Introduce clearer service and repository separation',
    description: 'Give project operations distinct service responsibilities before additional workflow features are added.',
    icon: 'layers',
    relatedEvidence: 'backend/app/routes/projects.py',
    evidenceLabel: 'Related evidence',
    action: 'Define a small project service layer between route handlers and persistence operations.',
    benefit: 'Keeps HTTP concerns separate from business decisions and reduces future route complexity.',
  },
  {
    category: 'Security',
    categoryTone: 'rose',
    priority: 'High',
    priorityTone: 'rose',
    title: 'Centralize environment configuration',
    description: 'Create one visible configuration boundary for secrets, database settings, and runtime behavior.',
    icon: 'code',
    relatedEvidence: 'backend/app/config.py',
    evidenceLabel: 'Related evidence',
    action: 'Route environment access through typed settings and document which values are required at runtime.',
    benefit: 'Reduces configuration drift and makes sensitive inputs easier to audit before deployment.',
  },
  {
    category: 'Security',
    categoryTone: 'rose',
    priority: 'High',
    priorityTone: 'rose',
    title: 'Add stronger input validation at the API boundary',
    description: 'Make invalid project input fail early with consistent, user-safe responses.',
    icon: 'activity',
    relatedEvidence: 'backend/app/schemas.py',
    evidenceLabel: 'Related evidence',
    action: 'Review request constraints and add explicit validation rules for project fields and lengths.',
    benefit: 'Protects downstream operations and gives clients clearer feedback when requests are incomplete.',
  },
  {
    category: 'Code Quality',
    categoryTone: 'amber',
    priority: 'Medium',
    priorityTone: 'amber',
    title: 'Separate route handlers into focused modules',
    description: 'Keep endpoint declarations small as the workflow gains additional project operations.',
    icon: 'folder',
    relatedEvidence: 'backend/app/routes/projects.py',
    evidenceLabel: 'Related evidence',
    action: 'Group related route concerns and extract repeated response or lookup behavior into named helpers.',
    benefit: 'Makes changes easier to review and lowers the chance of unrelated endpoint regressions.',
  },
  {
    category: 'Code Quality',
    categoryTone: 'amber',
    priority: 'Low',
    priorityTone: 'slate',
    title: 'Improve error handling structure',
    description: 'Use consistent error states across the workspace so failures remain visible without becoming noisy.',
    icon: 'activity',
    relatedEvidence: 'frontend/src/App.jsx',
    evidenceLabel: 'Related evidence',
    action: 'Define shared request-error presentation rules for loading, validation, and server failure states.',
    benefit: 'Creates a more predictable experience while keeping asynchronous UI logic easier to maintain.',
  },
  {
    category: 'Performance',
    categoryTone: 'cyan',
    priority: 'Medium',
    priorityTone: 'amber',
    title: 'Review database query patterns',
    description: 'Establish a habit of checking query shape before the project model expands beyond basic operations.',
    icon: 'database',
    relatedEvidence: 'backend/app/routes/projects.py',
    evidenceLabel: 'Related evidence',
    action: 'Inspect list and detail queries for avoidable repeated work, then add indexes where access patterns justify them.',
    benefit: 'Keeps common workspace requests responsive as project and finding counts increase.',
  },
  {
    category: 'Documentation',
    categoryTone: 'emerald',
    priority: 'Low',
    priorityTone: 'slate',
    title: 'Add API usage documentation',
    description: 'Capture the request and response shape that connects the dashboard to project operations.',
    icon: 'code',
    relatedEvidence: 'backend/app/main.py',
    evidenceLabel: 'Related evidence',
    action: 'Document the project endpoints with example payloads, expected errors, and local setup assumptions.',
    benefit: 'Shortens onboarding time and gives future UI work a stable contract to reference.',
  },
]