export const interviewSummary = {
  total: 12,
  easy: 4,
  medium: 5,
  hard: 3,
}

export const interviewQuestions = [
  {
    id: 'architecture-overview',
    question: 'Can you explain the overall architecture of this project?',
    category: 'Architecture',
    difficulty: 'Medium',
    relatedArea: 'Client, API, and persistence layers',
    relatedFile: 'frontend/src/components/WorkspaceView.jsx',
    whyAsked: 'This tests whether you can describe system boundaries and explain how the major pieces work together.',
    mockAnswer: 'The project is organized around a React and Vite client, a FastAPI backend, and a relational persistence layer. The frontend owns the workspace experience and calls a small API client, while backend routes coordinate project operations and database access. That separation gives each layer a clear responsibility and leaves room for future analysis workflows.',
    keyPoints: ['React and Vite provide the client workspace', 'FastAPI owns the HTTP boundary', 'Database access stays behind backend operations'],
  },
  {
    id: 'fastapi-choice',
    question: 'Why was FastAPI used for the backend?',
    category: 'Backend',
    difficulty: 'Easy',
    relatedArea: 'Python API service',
    relatedFile: 'backend/app/main.py',
    whyAsked: 'Interviewers use framework choices to understand how you weigh developer experience, contracts, and runtime needs.',
    mockAnswer: 'FastAPI is a practical fit for a Python service because it supports explicit request contracts, automatic API documentation, and an efficient development workflow. It also keeps the service surface lightweight while the product is still establishing its project and analysis flows.',
    keyPoints: ['Python aligns with the application context', 'Typed schemas make request contracts visible', 'Automatic docs improve API discoverability'],
  },
  {
    id: 'mysql-communication',
    question: 'How does the application communicate with MySQL?',
    category: 'Database',
    difficulty: 'Medium',
    relatedArea: 'Persistence and ORM access',
    relatedFile: 'backend/app/database.py',
    whyAsked: 'This reveals whether you can trace a request from an endpoint through the ORM to stored data.',
    mockAnswer: 'The backend uses SQLAlchemy as the ORM boundary for database access. Configuration creates the connection context, models describe the stored entities, and route operations use that persistence layer instead of embedding raw connection details in the client.',
    keyPoints: ['SQLAlchemy abstracts persistence operations', 'Database setup is a backend concern', 'The frontend communicates through API requests'],
  },
  {
    id: 'react-structure',
    question: 'How is the React frontend structured?',
    category: 'Frontend',
    difficulty: 'Easy',
    relatedArea: 'Dashboard shell and workspace components',
    relatedFile: 'frontend/src/App.jsx',
    whyAsked: 'A good answer demonstrates how you keep application state, layout, and reusable UI responsibilities separate.',
    mockAnswer: 'The root App component owns project-loading and creation state, then composes the dashboard header, workflow sidebar, and current workspace. Focused components render each workspace surface, while local data modules keep presentation examples separate from future API data.',
    keyPoints: ['App owns project CRUD state', 'Shell components define the shared layout', 'Workspace components keep feature UI focused'],
  },
  {
    id: 'api-communication',
    question: 'How does the frontend communicate with backend APIs?',
    category: 'API',
    difficulty: 'Medium',
    relatedArea: 'Project request client',
    relatedFile: 'frontend/src/api/client.js',
    whyAsked: 'This checks whether you can explain the contract between UI events and server operations.',
    mockAnswer: 'The frontend keeps request functions in a dedicated API client module. Components call those functions from event or effect handlers, update local loading and error state, and then render the returned project data. The architecture workspaces currently use mock presentation data and do not call analysis APIs.',
    keyPoints: ['Request details are centralized', 'UI state reflects loading and errors', 'Interview workspace data is intentionally local'],
  },
  {
    id: 'repository-safety',
    question: 'How would you protect uploaded repositories from unsafe execution?',
    category: 'Security',
    difficulty: 'Hard',
    relatedArea: 'Repository analysis boundary',
    relatedFile: 'Workspace context (future capability)',
    whyAsked: 'This evaluates threat modeling around untrusted source code, file content, and analysis tooling.',
    mockAnswer: 'I would treat every uploaded repository as untrusted. Analysis should run in an isolated, resource-limited environment with no unnecessary network or credential access, strict file and process boundaries, timeouts, and sanitized outputs. The service should also validate archive paths and record an auditable analysis lifecycle before exposing results to the workspace.',
    keyPoints: ['Isolate analysis from application credentials', 'Limit CPU, memory, time, and network access', 'Validate archives and sanitize returned content'],
  },
  {
    id: 'growth-decisions',
    question: 'What design decisions would you reconsider if this project grew significantly?',
    category: 'Project Design',
    difficulty: 'Hard',
    relatedArea: 'Workflow orchestration and data contracts',
    relatedFile: 'frontend/src/components/WorkflowSidebar.jsx',
    whyAsked: 'This invites you to discuss tradeoffs, future boundaries, and where a prototype would need stronger infrastructure.',
    mockAnswer: 'I would formalize workflow state instead of relying on a single statically mounted workspace, define versioned contracts for findings and suggestions, and move long-running repository analysis into background jobs. I would also add durable progress tracking and stronger observability before supporting multiple concurrent projects.',
    keyPoints: ['Formalize workflow and result contracts', 'Move expensive analysis to background jobs', 'Add durable progress and observability'],
  },
]